### PR TITLE
fix: not throw error in flushSync and end functions

### LINKED ISSUE #73: Fix syncFlush and end to not throw error
It should not throw exception when ThreadStream is destroyed.

Discussion in [pino-socket](https://github.com/pinojs/pino-socket/issues/59)

### PR DESCRIPTION
**Pull request by ramonmulia**
Closes #73 

we should apply the same logic made [here](https://github.com/pinojs/thread-stream/commit/ff7c9be4395ac871796773918a385a127c2be52f#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R262)  in `flushSync` and `end` functions.

discussion: https://github.com/pinojs/pino-socket/issues/59

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -249,9 +249,12 @@ class ThreadStream extends EventEmitter {
     return !this[kImpl].needDrain
   }
 
-  end () {
+  end (cb) {
     if (this[kImpl].destroyed) {
-      throw new Error('the worker has exited')
+      if (typeof cb === 'function') {
+        process.nextTick(cb, new Error('the worker has exited'))
+      }
```
Comment (mcollina) [inline index.js:256]: Please remove the callback and just return. There is no actual need to throw in this case.

File: index.js [hunk 2]
```diff
@@ -284,9 +287,12 @@ class ThreadStream extends EventEmitter {
     })
   }
 
-  flushSync () {
+  flushSync (cb) {
     if (this[kImpl].destroyed) {
-      throw new Error('the worker has exited')
+      if (typeof cb === 'function') {
+        process.nextTick(cb, new Error('the worker has exited'))
+      }
```
Comment (mcollina) [inline index.js:294]: flushSync is synchronous, so let's not have a callback. let's just silently return.

**Review by mcollina — CHANGES_REQUESTED** [review]

**Review by mcollina — APPROVED** [review]
lgtm
